language: java
script: "ant test_site"
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - ndushay@stanford.edu
    - laneymcg@stanford.edu
